development:
  cloud_name: "ddmovditn"
  api_key: "143535593614143"
  api_secret: "Q9de7cQcJbpoT07tQlz0xPuJsFc"
  enhance_image_tag: true
  static_file_support: false

production:
  cloud_name: "ddmovditn"
  api_key: "143535593614143"
  api_secret: "Q9de7cQcJbpoT07tQlz0xPuJsFc"
  enhance_image_tag: true
  static_file_support: true